2019-12-17 22:35:09,665:app:Exception on /info/room/1 [GET]
Traceback (most recent call last):
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\main\views\info_view.py", line 83, in room_specific
    room: Room_Data = cf.return_room_with_id(room_id)
  File "C:\Users\lewis\PycharmProjects\Hotel-La-Tour\main\data\database_or_cookie_funcs.py", line 256, in return_room_with_id
    logger.info(f"Returning room: {room.room_id}")
AttributeError: 'NoneType' object has no attribute 'room_id'
